################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/lvgl/demos/smartwatch/assets/img_alert_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_alipay_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_answer_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_app_info_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_application_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_back_file_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_bat_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_bin_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_brightness_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_bt_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_camera_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_chat_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_chrns_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_clock_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_cloud_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_custom_preview.c \
../Core/lvgl/demos/smartwatch/assets/img_digital_preview.c \
../Core/lvgl/demos/smartwatch/assets/img_directory_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_drive_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_facebook_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_file_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_game_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_info_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_instagram_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_kakao_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_kenya_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_language_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_line_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_mail_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_messenger_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_next_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_note_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_notify_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_pause_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_pay_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_paypal_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_penguin_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_play_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_qr_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_search_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_search_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_setting_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_skype_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_sms_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_telegram_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_timeout_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_twitter_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_unmute_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_viber_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_0.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_1.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_2.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_3.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_4.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_5.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_6.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_day_7.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_0.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_1.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_2.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_3.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_4.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_5.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_6.c \
../Core/lvgl/demos/smartwatch/assets/img_weather_night_7.c \
../Core/lvgl/demos/smartwatch/assets/img_web_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_wechat_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_weibo_icon.c \
../Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.c 

C_DEPS += \
./Core/lvgl/demos/smartwatch/assets/img_alert_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_alipay_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_answer_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_app_info_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_application_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_back_file_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_bat_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_bin_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_brightness_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_bt_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_camera_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_chat_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_chrns_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_clock_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_cloud_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_custom_preview.d \
./Core/lvgl/demos/smartwatch/assets/img_digital_preview.d \
./Core/lvgl/demos/smartwatch/assets/img_directory_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_drive_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_facebook_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_file_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_game_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_info_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_instagram_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_kakao_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_kenya_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_language_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_line_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_mail_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_messenger_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_next_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_note_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_notify_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_pause_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_pay_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_paypal_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_penguin_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_play_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_qr_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_search_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_search_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_setting_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_skype_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_sms_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_telegram_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_timeout_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_twitter_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_unmute_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_viber_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_0.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_1.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_2.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_3.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_4.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_5.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_6.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_7.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_0.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_1.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_2.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_3.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_4.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_5.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_6.d \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_7.d \
./Core/lvgl/demos/smartwatch/assets/img_web_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_wechat_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_weibo_icon.d \
./Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.d 

OBJS += \
./Core/lvgl/demos/smartwatch/assets/img_alert_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_alipay_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_answer_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_app_info_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_application_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_back_file_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_bat_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_bin_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_brightness_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_bt_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_camera_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_chat_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_chrns_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_clock_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_cloud_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_custom_preview.o \
./Core/lvgl/demos/smartwatch/assets/img_digital_preview.o \
./Core/lvgl/demos/smartwatch/assets/img_directory_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_drive_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_facebook_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_file_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_game_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_info_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_instagram_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_kakao_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_kenya_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_language_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_line_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_mail_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_messenger_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_next_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_note_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_notify_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_pause_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_pay_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_paypal_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_penguin_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_play_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_qr_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_search_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_search_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_setting_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_skype_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_sms_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_telegram_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_timeout_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_twitter_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_unmute_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_viber_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_0.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_1.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_2.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_3.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_4.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_5.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_6.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_day_7.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_0.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_1.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_2.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_3.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_4.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_5.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_6.o \
./Core/lvgl/demos/smartwatch/assets/img_weather_night_7.o \
./Core/lvgl/demos/smartwatch/assets/img_web_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_wechat_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_weibo_icon.o \
./Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.o 


# Each subdirectory must supply rules for building sources it contributes
Core/lvgl/demos/smartwatch/assets/%.o Core/lvgl/demos/smartwatch/assets/%.su Core/lvgl/demos/smartwatch/assets/%.cyclo: ../Core/lvgl/demos/smartwatch/assets/%.c Core/lvgl/demos/smartwatch/assets/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F746xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I../Core/lvgl -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-lvgl-2f-demos-2f-smartwatch-2f-assets

clean-Core-2f-lvgl-2f-demos-2f-smartwatch-2f-assets:
	-$(RM) ./Core/lvgl/demos/smartwatch/assets/img_alert_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_alert_icon.d ./Core/lvgl/demos/smartwatch/assets/img_alert_icon.o ./Core/lvgl/demos/smartwatch/assets/img_alert_icon.su ./Core/lvgl/demos/smartwatch/assets/img_alipay_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_alipay_icon.d ./Core/lvgl/demos/smartwatch/assets/img_alipay_icon.o ./Core/lvgl/demos/smartwatch/assets/img_alipay_icon.su ./Core/lvgl/demos/smartwatch/assets/img_answer_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_answer_icon.d ./Core/lvgl/demos/smartwatch/assets/img_answer_icon.o ./Core/lvgl/demos/smartwatch/assets/img_answer_icon.su ./Core/lvgl/demos/smartwatch/assets/img_app_info_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_app_info_icon.d ./Core/lvgl/demos/smartwatch/assets/img_app_info_icon.o ./Core/lvgl/demos/smartwatch/assets/img_app_info_icon.su ./Core/lvgl/demos/smartwatch/assets/img_application_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_application_icon.d ./Core/lvgl/demos/smartwatch/assets/img_application_icon.o ./Core/lvgl/demos/smartwatch/assets/img_application_icon.su ./Core/lvgl/demos/smartwatch/assets/img_back_file_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_back_file_icon.d ./Core/lvgl/demos/smartwatch/assets/img_back_file_icon.o ./Core/lvgl/demos/smartwatch/assets/img_back_file_icon.su ./Core/lvgl/demos/smartwatch/assets/img_bat_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_bat_icon.d ./Core/lvgl/demos/smartwatch/assets/img_bat_icon.o ./Core/lvgl/demos/smartwatch/assets/img_bat_icon.su ./Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.d ./Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.o ./Core/lvgl/demos/smartwatch/assets/img_battery_plugged_icon.su ./Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.d ./Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.o ./Core/lvgl/demos/smartwatch/assets/img_battery_state_icon.su ./Core/lvgl/demos/smartwatch/assets/img_bin_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_bin_icon.d ./Core/lvgl/demos/smartwatch/assets/img_bin_icon.o ./Core/lvgl/demos/smartwatch/assets/img_bin_icon.su ./Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.d ./Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.o ./Core/lvgl/demos/smartwatch/assets/img_ble_app_icon.su ./Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.d ./Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_bluetooth_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_brightness_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_brightness_icon.d ./Core/lvgl/demos/smartwatch/assets/img_brightness_icon.o ./Core/lvgl/demos/smartwatch/assets/img_brightness_icon.su ./Core/lvgl/demos/smartwatch/assets/img_bt_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_bt_icon.d ./Core/lvgl/demos/smartwatch/assets/img_bt_icon.o ./Core/lvgl/demos/smartwatch/assets/img_bt_icon.su ./Core/lvgl/demos/smartwatch/assets/img_camera_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_camera_icon.d ./Core/lvgl/demos/smartwatch/assets/img_camera_icon.o ./Core/lvgl/demos/smartwatch/assets/img_camera_icon.su ./Core/lvgl/demos/smartwatch/assets/img_chat_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_chat_icon.d ./Core/lvgl/demos/smartwatch/assets/img_chat_icon.o ./Core/lvgl/demos/smartwatch/assets/img_chat_icon.su ./Core/lvgl/demos/smartwatch/assets/img_chrns_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_chrns_icon.d ./Core/lvgl/demos/smartwatch/assets/img_chrns_icon.o ./Core/lvgl/demos/smartwatch/assets/img_chrns_icon.su ./Core/lvgl/demos/smartwatch/assets/img_clock_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_clock_icon.d ./Core/lvgl/demos/smartwatch/assets/img_clock_icon.o ./Core/lvgl/demos/smartwatch/assets/img_clock_icon.su ./Core/lvgl/demos/smartwatch/assets/img_cloud_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_cloud_icon.d ./Core/lvgl/demos/smartwatch/assets/img_cloud_icon.o ./Core/lvgl/demos/smartwatch/assets/img_cloud_icon.su ./Core/lvgl/demos/smartwatch/assets/img_custom_preview.cyclo ./Core/lvgl/demos/smartwatch/assets/img_custom_preview.d ./Core/lvgl/demos/smartwatch/assets/img_custom_preview.o ./Core/lvgl/demos/smartwatch/assets/img_custom_preview.su ./Core/lvgl/demos/smartwatch/assets/img_digital_preview.cyclo ./Core/lvgl/demos/smartwatch/assets/img_digital_preview.d ./Core/lvgl/demos/smartwatch/assets/img_digital_preview.o ./Core/lvgl/demos/smartwatch/assets/img_digital_preview.su ./Core/lvgl/demos/smartwatch/assets/img_directory_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_directory_icon.d ./Core/lvgl/demos/smartwatch/assets/img_directory_icon.o ./Core/lvgl/demos/smartwatch/assets/img_directory_icon.su ./Core/lvgl/demos/smartwatch/assets/img_drive_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_drive_icon.d ./Core/lvgl/demos/smartwatch/assets/img_drive_icon.o ./Core/lvgl/demos/smartwatch/assets/img_drive_icon.su ./Core/lvgl/demos/smartwatch/assets/img_facebook_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_facebook_icon.d ./Core/lvgl/demos/smartwatch/assets/img_facebook_icon.o ./Core/lvgl/demos/smartwatch/assets/img_facebook_icon.su ./Core/lvgl/demos/smartwatch/assets/img_file_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_file_icon.d ./Core/lvgl/demos/smartwatch/assets/img_file_icon.o ./Core/lvgl/demos/smartwatch/assets/img_file_icon.su ./Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.d ./Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.o ./Core/lvgl/demos/smartwatch/assets/img_file_manager_icon.su ./Core/lvgl/demos/smartwatch/assets/img_game_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_game_icon.d
	-$(RM) ./Core/lvgl/demos/smartwatch/assets/img_game_icon.o ./Core/lvgl/demos/smartwatch/assets/img_game_icon.su ./Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.d ./Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.o ./Core/lvgl/demos/smartwatch/assets/img_general_settings_icon.su ./Core/lvgl/demos/smartwatch/assets/img_info_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_info_icon.d ./Core/lvgl/demos/smartwatch/assets/img_info_icon.o ./Core/lvgl/demos/smartwatch/assets/img_info_icon.su ./Core/lvgl/demos/smartwatch/assets/img_instagram_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_instagram_icon.d ./Core/lvgl/demos/smartwatch/assets/img_instagram_icon.o ./Core/lvgl/demos/smartwatch/assets/img_instagram_icon.su ./Core/lvgl/demos/smartwatch/assets/img_kakao_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_kakao_icon.d ./Core/lvgl/demos/smartwatch/assets/img_kakao_icon.o ./Core/lvgl/demos/smartwatch/assets/img_kakao_icon.su ./Core/lvgl/demos/smartwatch/assets/img_kenya_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_kenya_icon.d ./Core/lvgl/demos/smartwatch/assets/img_kenya_icon.o ./Core/lvgl/demos/smartwatch/assets/img_kenya_icon.su ./Core/lvgl/demos/smartwatch/assets/img_language_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_language_icon.d ./Core/lvgl/demos/smartwatch/assets/img_language_icon.o ./Core/lvgl/demos/smartwatch/assets/img_language_icon.su ./Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.d ./Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.o ./Core/lvgl/demos/smartwatch/assets/img_left_arrow_icon.su ./Core/lvgl/demos/smartwatch/assets/img_line_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_line_icon.d ./Core/lvgl/demos/smartwatch/assets/img_line_icon.o ./Core/lvgl/demos/smartwatch/assets/img_line_icon.su ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.d ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.o ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_black_icon.su ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.d ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.o ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_blue_icon.su ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.d ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.o ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_green_icon.su ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.d ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.o ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_icon.su ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.d ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.o ./Core/lvgl/demos/smartwatch/assets/img_lvgl_logo_red_icon.su ./Core/lvgl/demos/smartwatch/assets/img_mail_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_mail_icon.d ./Core/lvgl/demos/smartwatch/assets/img_mail_icon.o ./Core/lvgl/demos/smartwatch/assets/img_mail_icon.su ./Core/lvgl/demos/smartwatch/assets/img_messenger_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_messenger_icon.d ./Core/lvgl/demos/smartwatch/assets/img_messenger_icon.o ./Core/lvgl/demos/smartwatch/assets/img_messenger_icon.su ./Core/lvgl/demos/smartwatch/assets/img_next_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_next_g_icon.d ./Core/lvgl/demos/smartwatch/assets/img_next_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_next_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_note_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_note_icon.d ./Core/lvgl/demos/smartwatch/assets/img_note_icon.o ./Core/lvgl/demos/smartwatch/assets/img_note_icon.su ./Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.d ./Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.o ./Core/lvgl/demos/smartwatch/assets/img_notifications_app_icon.su ./Core/lvgl/demos/smartwatch/assets/img_notify_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_notify_icon.d ./Core/lvgl/demos/smartwatch/assets/img_notify_icon.o ./Core/lvgl/demos/smartwatch/assets/img_notify_icon.su ./Core/lvgl/demos/smartwatch/assets/img_pause_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_pause_icon.d ./Core/lvgl/demos/smartwatch/assets/img_pause_icon.o ./Core/lvgl/demos/smartwatch/assets/img_pause_icon.su ./Core/lvgl/demos/smartwatch/assets/img_pay_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_pay_icon.d ./Core/lvgl/demos/smartwatch/assets/img_pay_icon.o ./Core/lvgl/demos/smartwatch/assets/img_pay_icon.su ./Core/lvgl/demos/smartwatch/assets/img_paypal_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_paypal_icon.d ./Core/lvgl/demos/smartwatch/assets/img_paypal_icon.o ./Core/lvgl/demos/smartwatch/assets/img_paypal_icon.su ./Core/lvgl/demos/smartwatch/assets/img_penguin_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_penguin_icon.d ./Core/lvgl/demos/smartwatch/assets/img_penguin_icon.o ./Core/lvgl/demos/smartwatch/assets/img_penguin_icon.su ./Core/lvgl/demos/smartwatch/assets/img_play_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_play_icon.d ./Core/lvgl/demos/smartwatch/assets/img_play_icon.o ./Core/lvgl/demos/smartwatch/assets/img_play_icon.su ./Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.d ./Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_play_pause_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.d
	-$(RM) ./Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_previous_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_qr_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_qr_icon.d ./Core/lvgl/demos/smartwatch/assets/img_qr_icon.o ./Core/lvgl/demos/smartwatch/assets/img_qr_icon.su ./Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.d ./Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.o ./Core/lvgl/demos/smartwatch/assets/img_right_arrow_icon.su ./Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.d ./Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.o ./Core/lvgl/demos/smartwatch/assets/img_screen_rotate_icon.su ./Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.d ./Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.o ./Core/lvgl/demos/smartwatch/assets/img_scrolling_icon.su ./Core/lvgl/demos/smartwatch/assets/img_search_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_search_g_icon.d ./Core/lvgl/demos/smartwatch/assets/img_search_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_search_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_search_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_search_icon.d ./Core/lvgl/demos/smartwatch/assets/img_search_icon.o ./Core/lvgl/demos/smartwatch/assets/img_search_icon.su ./Core/lvgl/demos/smartwatch/assets/img_setting_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_setting_icon.d ./Core/lvgl/demos/smartwatch/assets/img_setting_icon.o ./Core/lvgl/demos/smartwatch/assets/img_setting_icon.su ./Core/lvgl/demos/smartwatch/assets/img_skype_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_skype_icon.d ./Core/lvgl/demos/smartwatch/assets/img_skype_icon.o ./Core/lvgl/demos/smartwatch/assets/img_skype_icon.su ./Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.d ./Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.o ./Core/lvgl/demos/smartwatch/assets/img_smartwatch_icon.su ./Core/lvgl/demos/smartwatch/assets/img_sms_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_sms_icon.d ./Core/lvgl/demos/smartwatch/assets/img_sms_icon.o ./Core/lvgl/demos/smartwatch/assets/img_sms_icon.su ./Core/lvgl/demos/smartwatch/assets/img_telegram_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_telegram_icon.d ./Core/lvgl/demos/smartwatch/assets/img_telegram_icon.o ./Core/lvgl/demos/smartwatch/assets/img_telegram_icon.su ./Core/lvgl/demos/smartwatch/assets/img_timeout_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_timeout_icon.d ./Core/lvgl/demos/smartwatch/assets/img_timeout_icon.o ./Core/lvgl/demos/smartwatch/assets/img_timeout_icon.su ./Core/lvgl/demos/smartwatch/assets/img_twitter_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_twitter_icon.d ./Core/lvgl/demos/smartwatch/assets/img_twitter_icon.o ./Core/lvgl/demos/smartwatch/assets/img_twitter_icon.su ./Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.d ./Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.o ./Core/lvgl/demos/smartwatch/assets/img_twitter_x_icon.su ./Core/lvgl/demos/smartwatch/assets/img_unmute_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_unmute_icon.d ./Core/lvgl/demos/smartwatch/assets/img_unmute_icon.o ./Core/lvgl/demos/smartwatch/assets/img_unmute_icon.su ./Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.d ./Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.o ./Core/lvgl/demos/smartwatch/assets/img_up_arrow_icon.su ./Core/lvgl/demos/smartwatch/assets/img_viber_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_viber_icon.d ./Core/lvgl/demos/smartwatch/assets/img_viber_icon.o ./Core/lvgl/demos/smartwatch/assets/img_viber_icon.su ./Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.d ./Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.o ./Core/lvgl/demos/smartwatch/assets/img_vkontakte_icon.su ./Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.d ./Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.o ./Core/lvgl/demos/smartwatch/assets/img_vol_down_icon.su ./Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.d ./Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.o ./Core/lvgl/demos/smartwatch/assets/img_vol_up_icon.su ./Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.d ./Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_volume_down_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.d ./Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.o ./Core/lvgl/demos/smartwatch/assets/img_volupe_up_g_icon.su ./Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.d ./Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.o ./Core/lvgl/demos/smartwatch/assets/img_weather_app_icon.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_0.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_0.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_0.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_0.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_1.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_1.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_1.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_1.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_2.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_2.d
	-$(RM) ./Core/lvgl/demos/smartwatch/assets/img_weather_day_2.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_2.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_3.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_3.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_3.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_3.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_4.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_4.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_4.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_4.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_5.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_5.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_5.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_5.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_6.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_6.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_6.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_6.su ./Core/lvgl/demos/smartwatch/assets/img_weather_day_7.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_day_7.d ./Core/lvgl/demos/smartwatch/assets/img_weather_day_7.o ./Core/lvgl/demos/smartwatch/assets/img_weather_day_7.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_0.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_0.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_0.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_0.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_1.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_1.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_1.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_1.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_2.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_2.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_2.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_2.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_3.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_3.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_3.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_3.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_4.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_4.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_4.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_4.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_5.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_5.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_5.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_5.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_6.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_6.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_6.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_6.su ./Core/lvgl/demos/smartwatch/assets/img_weather_night_7.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weather_night_7.d ./Core/lvgl/demos/smartwatch/assets/img_weather_night_7.o ./Core/lvgl/demos/smartwatch/assets/img_weather_night_7.su ./Core/lvgl/demos/smartwatch/assets/img_web_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_web_icon.d ./Core/lvgl/demos/smartwatch/assets/img_web_icon.o ./Core/lvgl/demos/smartwatch/assets/img_web_icon.su ./Core/lvgl/demos/smartwatch/assets/img_wechat_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_wechat_icon.d ./Core/lvgl/demos/smartwatch/assets/img_wechat_icon.o ./Core/lvgl/demos/smartwatch/assets/img_wechat_icon.su ./Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.d ./Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.o ./Core/lvgl/demos/smartwatch/assets/img_wechat_pay_icon.su ./Core/lvgl/demos/smartwatch/assets/img_weibo_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_weibo_icon.d ./Core/lvgl/demos/smartwatch/assets/img_weibo_icon.o ./Core/lvgl/demos/smartwatch/assets/img_weibo_icon.su ./Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.cyclo ./Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.d ./Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.o ./Core/lvgl/demos/smartwatch/assets/img_whatsapp_icon.su

.PHONY: clean-Core-2f-lvgl-2f-demos-2f-smartwatch-2f-assets

